Mutation:
    type: object
    config:
        fields:
            createTask:
                type: "Task"
                args:
                    title:
                        type: "String!"
                    description:
                        type: "String!"
                    userId:
                        type: "String"
                resolve: "@=service('TaskMutation').create(args)"
            syncUsers:
                type: "Boolean!"
                resolve: "@=service('UserMutation').sync()"
            changeTaskStatus:
                type: "Task"
                args:
                    id:
                        type: "String!"
                    status:
                        type: "TaskStatus!"
                resolve: "@=service('TaskMutation').changeStatus(args['id'], args['status'])"
