Query:
    type: object
    config:
        fields:
            healthCheck:
                type: "String"
                resolve: "ok"
            allTasks:
                type: "[Task]"
                resolve: "@=service('App\\Domain\\Task\\TaskRepositoryInterface').findAll()"
            allUsers:
                type: "[User]!"
                resolve: "@=service('App\\Domain\\User\\UserRepositoryInterface').findAll()"
