Query:
    type: object
    config:
        fields:
            healthCheck:
                type: "String"
                resolve: "ok"
            allTasks:
                type: "[Task]"
                resolve: "@=service('task.repository').findAll()"
            allUsers:
                type: "[User]!"
                resolve: "@=service('user.repository').findAll()"
