Task:
    type: object
    config:
        description: "Reprezentuje zadanie w systemie"
        fields:
            id:
                type: "String!"
                resolve: "@=value.getId().toRfc4122()"
            title:
                type: "String!"
            description:
                type: "String!"
            status:
                type: "String!"
            user:
                type: "User"
                resolve: "@=value.getUserId() ? service('user.repository').find(value.getUserId().toRfc4122()) : null"
