# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.github_url: '%env(GITHUB_REPO_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    TaskMutation:
        class: App\Infrastructure\GraphQL\Mutation\TaskMutation
        public: true
        arguments:
            $commandBus: '@command.bus'
            $taskRepository: '@App\Domain\Task\TaskRepositoryInterface'
        tags:
            - { name: overblog_graphql.mutation, alias: "TaskMutation" }

    UserMutation:
        class: App\Infrastructure\GraphQL\Mutation\UserMutation
        public: true
        arguments:
            $commandBus: '@command.bus'
        tags:
            - { name: overblog_graphql.mutation, alias: "UserMutation" }    # add more service definitions when explicit configuration is needed

    user.repository:
        alias: 'App\Domain\User\UserRepositoryInterface'
        public: true

    task.repository:
        alias: 'App\Domain\Task\TaskRepositoryInterface'
        public: true

